server:
  port: 8082

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.lanqiao.studentdormitory.pojo
spring:
  datasource:
    url: jdbc:mysql://47.109.206.82/dm?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 20010720Lmx
  thymeleaf:
    cache: false
    check-template-location: 'true'
    mode: HTML5
    prefix: 'classpath:/templates/'
    suffix: '.html'
    servlet:
      content-type: 'text/html '
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 10MB
  mvc:
    contentnegotiation:
      favor-parameter: true
    jackson:
      default-property-inclusion: non_null
image:
  path: classpath:/CaptchaImage/

