server:
  port: 8082

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.lanqiao.studentdormitory.pojo
spring:
  datasource:
    username: root
    password: 20010720Lmx
    url: jdbc:mysql://lmxdxl99.com.cn/dm?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template-location: 'true'
    mode: HTML5
    prefix: 'classpath:/templates/'
    suffix: '.html'
    servlet:
      content-type: 'text/html '
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100000000
image:
  path: classpath:/CaptchaImage/